version: "3"

services:
  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - front:/app
    ports:
      - "3000:3000"
    restart: always

  back:
    container_name: back
    networks:
      - database
    build:
      context: back
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - back:/app
    ports:
      - "3001:3001"
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    container_name: database
    networks:
      - database
    volumes:
      - database:/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  front:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "front/docker-storage"
  back:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "back/docker-storage"
  database:
#    driver: local
#    driver_opts:
#      type: "none"
#      o: "bind"
#      device: "database/docker-storage"

networks:
  database:
    driver: bridge
