version: "3"

services:
#  nginx:
#    container_name: nginx
#    volumes:
#      - front:/var/www/html/front
#    networks:
#      - front
#    depends_on:
#      - front
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    ports:
#      - "443:443"

  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - front:/app
    ports:
      - "3000:3000"
    restart: always

  back:
    container_name: back
    networks:
      - db
    build:
      context: back
      dockerfile: Dockerfile
    volumes:
      - back:/app
    ports:
      - "3001:3000"
#    depends_on:
#      - db
#
#  db:
#    container_name: db
#    networks:
#      - db
#    build:
#      context: back
#      dockerfile: Dockerfile

volumes:
  front:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/nfs/homes/marobert/transcendence/front/docker-storage'
  back:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/nfs/homes/marobert/transcendence/back/docker-storage'
#  db:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/nfs/homes/marobert/transcendance/data/db'


networks:
  db:
    driver: bridge